/**
 * @description - Contains the name for user Profile
 */
const USERProfile = {
  USER_PROFILE: "USER_PROFILE",
  USER_PROFILE_RESPONSE: "USER_PROFILE_RESPONSE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_RESPONSE: "USER_LOGIN_RESPONSE",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  VERIFY_EMAIL_RESPONSE: "VERIFY_EMAIL_RESPONSE",
  VERFY_SECURITY_QUESTION: "VERFY_SECURITY_QUESTION",
  VERFY_SECURITY_QUESTION_RESPONSE: "VERFY_SECURITY_QUESTION_RESPONSE",
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_RESPONSE: "RESET_PASSWORD_RESPONSE"
};

export default USERProfile;
